spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ArtFusion
    username: sa
    password:
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl_auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  ai:
    openai:
      api-key: ${OPEN_AI_ACCESS_KEY}
      gpt-url: ${OPEN_AI_GPT_URL}

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    bucket: ${AWS_BUCKET_NAME}
    region: ${AWS_REGION}


